param(
  [Parameter(Position = 0)]
  [string]$Command = "doctor",

  [Parameter(Position = 1)]
  [string]$Target = "",

  [string]$Source = "",

  [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Header {
  param([Parameter(Mandatory = $true)][string]$Text)
  Write-Host ""
  Write-Host "== AIOS :: $Text ==" -ForegroundColor Cyan
}

function Test-AiosFile {
  param([Parameter(Mandatory = $true)][string]$Path)
  if (Test-Path -LiteralPath $Path) {
    Write-Host "[OK] $Path" -ForegroundColor Green
    return $true
  }
  Write-Host "[MISSING] $Path" -ForegroundColor Red
  return $false
}

function Ensure-Directory {
  param([Parameter(Mandatory = $true)][string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Path $Path -Force | Out-Null
  }
}

function Copy-AiosContent {
  param(
    [Parameter(Mandatory = $true)][string]$From,
    [Parameter(Mandatory = $true)][string]$To
  )
  if (-not (Test-Path -LiteralPath $From)) { throw "Source not found: $From" }
  Ensure-Directory -Path $To
  Get-ChildItem -LiteralPath $From -Force | Copy-Item -Destination $To -Recurse -Force
}

function Resolve-AiosSource {
  param([string]$RequestedSource)
  if (-not [string]::IsNullOrWhiteSpace($RequestedSource)) {
    if (-not (Test-Path -LiteralPath $RequestedSource)) { throw "AIOS source not found: $RequestedSource" }
    return (Resolve-Path -LiteralPath $RequestedSource).Path
  }
  $defaultSource = "C:\GitHub\AIOS-Enterprise"
  if (Test-Path -LiteralPath $defaultSource) { return $defaultSource }
  throw "AIOS source not found. Use -Source C:\GitHub\AIOS-Enterprise"
}

function New-AiosBug {
  param(
    [Parameter(Mandatory = $true)][string]$Id,
    [Parameter(Mandatory = $true)][string]$Title
  )

  Ensure-Directory -Path ".\docs\bugs"
  Ensure-Directory -Path ".\docs\acceptance"

  $bugPath = ".\docs\bugs\$Id.md"
  $acceptancePath = ".\docs\acceptance\$Id.md"

  if ((Test-Path -LiteralPath $bugPath) -and (-not $Force)) {
    throw "Bug file already exists: $bugPath. Use -Force to overwrite."
  }

  $branch = "Unknown"
  try {
    $candidate = (& git branch --show-current 2>$null).Trim()
    if (-not [string]::IsNullOrWhiteSpace($candidate)) { $branch = $candidate }
  } catch {}

  $bugContent = @"
# ${Id}: $Title

## Observed Behavior

Describe what is currently going wrong.

## Expected Behavior

Describe what should happen instead.

## Evidence

- Branch: $branch
- Console:
- Test:
- Screenshot:
- User report:

## Affected Area

Unknown until Context Builder resolves scope.

## AIOS Notes

Generated by AIOS v9.1 NightWatch.
"@

  $acceptanceContent = @"
# Acceptance Criteria: $Id

## Must Pass

- The observed issue is addressed.
- The expected behavior is satisfied.
- The fix is limited to the affected scope.
- No unrelated files are modified.
- Verification result is documented.
"@

  Set-Content -LiteralPath $bugPath -Value $bugContent -Encoding UTF8
  Set-Content -LiteralPath $acceptancePath -Value $acceptanceContent -Encoding UTF8

  Write-Host "Created: $bugPath"
  Write-Host "Created: $acceptancePath"
}

switch ($Command.ToLowerInvariant()) {
  "doctor" {
    Write-Header -Text "Doctor"
    $requiredFiles = @(
      ".aios/aios.config.yaml",
      ".aios/kernel/kernel.yaml",
      ".aios/runtime/runtime.yaml",
      ".aios/workflows/bugfix.yaml",
      ".aios/workflows/solve.yaml",
      ".aios/policies/default.yaml",
      ".aios/version.json",
      ".aios/installer/manifest.json",
      ".aios/daemon/daemon.yaml",
      ".aios/detectors/bug-detector.yaml",
      ".aios/generators/acceptance-generator.yaml",
      ".aios/context/context-builder.yaml",
      ".aios/runtime/watch-state.json",
      "scripts/aios-watch.ps1",
      "scripts/aios-capture.ps1",
      "scripts/aios-service.ps1"
    )
    $missing = 0
    foreach ($file in $requiredFiles) {
      if (-not (Test-AiosFile -Path $file)) { $missing++ }
    }
    Write-Host ""
    if ($missing -eq 0) {
      Write-Host "AIOS doctor completed: HEALTHY" -ForegroundColor Green
      exit 0
    }
    Write-Host "AIOS doctor completed: $missing required file(s) missing." -ForegroundColor Red
    exit 1
  }

  "install" {
    Write-Header -Text "Install"
    $resolvedSource = Resolve-AiosSource -RequestedSource $Source
    Copy-AiosContent -From "$resolvedSource\.aios" -To ".\.aios"
    Copy-AiosContent -From "$resolvedSource\scripts" -To ".\scripts"
    Copy-AiosContent -From "$resolvedSource\templates" -To ".\templates"
    Ensure-Directory -Path ".\docs"
    foreach ($doc in @("runtime.md", "auto-bug.md", "nightwatch.md")) {
      if (Test-Path -LiteralPath "$resolvedSource\docs\$doc") {
        Copy-Item -LiteralPath "$resolvedSource\docs\$doc" -Destination ".\docs\$doc" -Force
      }
    }
    foreach ($rootFile in @("AIOS_START.md", "AIOS_HANDOFF.md")) {
      if (Test-Path -LiteralPath "$resolvedSource\$rootFile") {
        Copy-Item -LiteralPath "$resolvedSource\$rootFile" -Destination ".\$rootFile" -Force
      }
    }
    Write-Host "AIOS installed." -ForegroundColor Green
  }

  "update" {
    Write-Header -Text "Update"
    $resolvedSource = Resolve-AiosSource -RequestedSource $Source
    Copy-AiosContent -From "$resolvedSource\.aios" -To ".\.aios"
    Copy-AiosContent -From "$resolvedSource\scripts" -To ".\scripts"
    Copy-AiosContent -From "$resolvedSource\templates" -To ".\templates"
    Ensure-Directory -Path ".\docs"
    foreach ($doc in @("runtime.md", "auto-bug.md", "nightwatch.md")) {
      if (Test-Path -LiteralPath "$resolvedSource\docs\$doc") {
        Copy-Item -LiteralPath "$resolvedSource\docs\$doc" -Destination ".\docs\$doc" -Force
      }
    }
    foreach ($rootFile in @("AIOS_START.md", "AIOS_HANDOFF.md")) {
      if (Test-Path -LiteralPath "$resolvedSource\$rootFile") {
        Copy-Item -LiteralPath "$resolvedSource\$rootFile" -Destination ".\$rootFile" -Force
      }
    }
    Write-Host "AIOS updated." -ForegroundColor Green
  }

  "bug" {
    Write-Header -Text "Bug"
    if ([string]::IsNullOrWhiteSpace($Target)) {
      $Target = "BUG-" + (Get-Date -Format "yyyyMMdd-HHmmss")
    }
    New-AiosBug -Id $Target -Title "Auto Generated Bug"
  }

  "solve" {
    Write-Header -Text "Solve"
    if ([string]::IsNullOrWhiteSpace($Target)) {
      $Target = "BUG-" + (Get-Date -Format "yyyyMMdd-HHmmss")
      New-AiosBug -Id $Target -Title "Auto Detected Bug"
    }
    Write-Host "Target: $Target"
    Write-Host "Next: use templates/AIOS_V9_SOLVE_PROMPT.md in your AI CLI."
  }

  "watch-install" {
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File ".\scripts\aios-service.ps1" install -ProjectRoot (Get-Location).Path
  }

  "watch-start" {
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File ".\scripts\aios-service.ps1" start -ProjectRoot (Get-Location).Path
  }

  "watch-stop" {
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File ".\scripts\aios-service.ps1" stop -ProjectRoot (Get-Location).Path
  }

  "watch-status" {
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File ".\scripts\aios-service.ps1" status -ProjectRoot (Get-Location).Path
  }

  "watch-uninstall" {
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File ".\scripts\aios-service.ps1" uninstall -ProjectRoot (Get-Location).Path
  }

  "watch-once" {
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File ".\scripts\aios-service.ps1" run-once -ProjectRoot (Get-Location).Path
  }

  "queue" {
    Write-Header -Text "Queue"
    Ensure-Directory -Path ".\.aios\queue"
    $items = Get-ChildItem -LiteralPath ".\.aios\queue" -Filter "*.json" -ErrorAction SilentlyContinue
    if (-not $items) {
      Write-Host "Queue is empty."
    } else {
      $items | ForEach-Object {
        $data = Get-Content -LiteralPath $_.FullName -Raw | ConvertFrom-Json
        Write-Host "$($data.bug_id) [$($data.status)] $($data.source_log)"
      }
    }
  }

  "handoff-update" {
    & powershell.exe -NoProfile -ExecutionPolicy Bypass `
      -File ".\scripts\aios-handoff.ps1" `
      -ProjectRoot (Get-Location).Path
  }

  "handoff-status" {
    Write-Header -Text "Handoff Status"
    if (-not (Test-Path -LiteralPath ".\.aios\runtime\project-state.json")) {
      throw "Project state file is missing. Run handoff-update first."
    }
    Get-Content -LiteralPath ".\.aios\runtime\project-state.json" -Raw
  }

  default {
    throw "Unknown command: $Command"
  }
}
