param(
  [Parameter(Position = 0)]
  [string]$Command = "doctor",

  [Parameter(Position = 1)]
  [string]$Target = "",

  [string]$Source = "",

  [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Header {
  param([Parameter(Mandatory = $true)][string]$Text)

  Write-Host ""
  Write-Host "== AIOS :: $Text ==" -ForegroundColor Cyan
}

function Test-AiosFile {
  param([Parameter(Mandatory = $true)][string]$Path)

  if (Test-Path -LiteralPath $Path) {
    Write-Host "[OK] $Path" -ForegroundColor Green
    return $true
  }

  Write-Host "[MISSING] $Path" -ForegroundColor Red
  return $false
}

function Ensure-Directory {
  param([Parameter(Mandatory = $true)][string]$Path)

  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Path $Path -Force | Out-Null
  }
}

function Copy-AiosContent {
  param(
    [Parameter(Mandatory = $true)][string]$From,
    [Parameter(Mandatory = $true)][string]$To
  )

  if (-not (Test-Path -LiteralPath $From)) {
    throw "Source not found: $From"
  }

  Ensure-Directory -Path $To
  Get-ChildItem -LiteralPath $From -Force | Copy-Item -Destination $To -Recurse -Force
}

function Resolve-AiosSource {
  param([string]$RequestedSource)

  if (-not [string]::IsNullOrWhiteSpace($RequestedSource)) {
    if (-not (Test-Path -LiteralPath $RequestedSource)) {
      throw "AIOS source not found: $RequestedSource"
    }
    return (Resolve-Path -LiteralPath $RequestedSource).Path
  }

  $defaultSource = "C:\GitHub\AIOS-Enterprise"
  if (Test-Path -LiteralPath $defaultSource) {
    return $defaultSource
  }

  throw "AIOS source not found. Use -Source C:\GitHub\AIOS-Enterprise"
}

function New-AiosBug {
  param(
    [Parameter(Mandatory = $true)][string]$Id,
    [Parameter(Mandatory = $true)][string]$Title
  )

  Ensure-Directory -Path ".\docs\bugs"
  Ensure-Directory -Path ".\docs\acceptance"

  $bugPath = ".\docs\bugs\$Id.md"
  $acceptancePath = ".\docs\acceptance\$Id.md"

  if ((Test-Path -LiteralPath $bugPath) -and (-not $Force)) {
    throw "Bug file already exists: $bugPath. Use -Force to overwrite."
  }

  $branch = ""
  try {
    $branch = (& git branch --show-current 2>$null).Trim()
  } catch {
    $branch = ""
  }

  if ([string]::IsNullOrWhiteSpace($branch)) {
    $branch = "Unknown"
  }

  $bugContent = @"
# ${Id}: $Title

## Observed Behavior

Describe what is currently going wrong.

## Expected Behavior

Describe what should happen instead.

## Evidence

- Branch: $branch
- Console:
- Test:
- Screenshot:
- User report:

## Affected Area

Unknown until Context Builder resolves scope.

## AIOS Notes

Generated by AIOS v9.0.1 BugHarvester Patch 1.
"@

  $acceptanceContent = @"
# Acceptance Criteria: $Id

## Must Pass

- The observed issue is addressed.
- The expected behavior is satisfied.
- The fix is limited to the affected scope.
- No unrelated files are modified.
- Verification result is documented.

## Verification Steps

1. Reproduce or clearly explain the issue.
2. Apply the repair.
3. Verify the expected behavior.
4. Confirm no regression in nearby behavior.

## Acceptance Mapping

| Criteria | Status | Evidence |
|---|---|---|
| Issue addressed | Pending | |
| Expected behavior met | Pending | |
| Scope controlled | Pending | |
| Verification complete | Pending | |
"@

  Set-Content -LiteralPath $bugPath -Value $bugContent -Encoding UTF8
  Set-Content -LiteralPath $acceptancePath -Value $acceptanceContent -Encoding UTF8

  Write-Host "Created: $bugPath"
  Write-Host "Created: $acceptancePath"
}

switch ($Command.ToLowerInvariant()) {
  "doctor" {
    Write-Header -Text "Doctor"

    $requiredFiles = @(
      ".aios/aios.config.yaml",
      ".aios/kernel/kernel.yaml",
      ".aios/runtime/runtime.yaml",
      ".aios/workflows/bugfix.yaml",
      ".aios/workflows/solve.yaml",
      ".aios/policies/default.yaml",
      ".aios/version.json",
      ".aios/installer/manifest.json",
      ".aios/daemon/daemon.yaml",
      ".aios/detectors/bug-detector.yaml",
      ".aios/generators/acceptance-generator.yaml",
      ".aios/context/context-builder.yaml"
    )

    $missing = 0
    foreach ($file in $requiredFiles) {
      if (-not (Test-AiosFile -Path $file)) {
        $missing++
      }
    }

    Write-Host ""
    if ($missing -eq 0) {
      Write-Host "AIOS doctor completed: HEALTHY" -ForegroundColor Green
      exit 0
    }

    Write-Host "AIOS doctor completed: $missing required file(s) missing." -ForegroundColor Red
    exit 1
  }

  "install" {
    Write-Header -Text "Install"
    $resolvedSource = Resolve-AiosSource -RequestedSource $Source

    Write-Host "Source: $resolvedSource"
    Write-Host "Target: $(Get-Location)"

    Copy-AiosContent -From "$resolvedSource\.aios" -To ".\.aios"
    Copy-AiosContent -From "$resolvedSource\scripts" -To ".\scripts"
    Copy-AiosContent -From "$resolvedSource\templates" -To ".\templates"

    Ensure-Directory -Path ".\docs"
    if (Test-Path -LiteralPath "$resolvedSource\docs\runtime.md") {
      Copy-Item -LiteralPath "$resolvedSource\docs\runtime.md" -Destination ".\docs\runtime.md" -Force
    }
    if (Test-Path -LiteralPath "$resolvedSource\docs\auto-bug.md") {
      Copy-Item -LiteralPath "$resolvedSource\docs\auto-bug.md" -Destination ".\docs\auto-bug.md" -Force
    }

    Write-Host "AIOS installed." -ForegroundColor Green
  }

  "update" {
    Write-Header -Text "Update"
    $resolvedSource = Resolve-AiosSource -RequestedSource $Source

    Write-Host "Source: $resolvedSource"
    Write-Host "Target: $(Get-Location)"

    Copy-AiosContent -From "$resolvedSource\.aios" -To ".\.aios"
    Copy-AiosContent -From "$resolvedSource\scripts" -To ".\scripts"
    Copy-AiosContent -From "$resolvedSource\templates" -To ".\templates"

    Ensure-Directory -Path ".\docs"
    if (Test-Path -LiteralPath "$resolvedSource\docs\runtime.md") {
      Copy-Item -LiteralPath "$resolvedSource\docs\runtime.md" -Destination ".\docs\runtime.md" -Force
    }
    if (Test-Path -LiteralPath "$resolvedSource\docs\auto-bug.md") {
      Copy-Item -LiteralPath "$resolvedSource\docs\auto-bug.md" -Destination ".\docs\auto-bug.md" -Force
    }

    Write-Host "AIOS updated." -ForegroundColor Green
  }

  "sync" {
    Write-Header -Text "Sync"
    $resolvedSource = Resolve-AiosSource -RequestedSource $Source

    Copy-AiosContent -From "$resolvedSource\.aios" -To ".\.aios"
    Copy-AiosContent -From "$resolvedSource\scripts" -To ".\scripts"
    Copy-AiosContent -From "$resolvedSource\templates" -To ".\templates"

    Write-Host "AIOS sync completed." -ForegroundColor Green
  }

  "bug" {
    Write-Header -Text "Bug"

    if ([string]::IsNullOrWhiteSpace($Target)) {
      $Target = "BUG-" + (Get-Date -Format "yyyyMMdd-HHmmss")
    }

    New-AiosBug -Id $Target -Title "Auto Generated Bug"
  }

  "solve" {
    Write-Header -Text "Solve"

    if ([string]::IsNullOrWhiteSpace($Target)) {
      $Target = "BUG-" + (Get-Date -Format "yyyyMMdd-HHmmss")
      New-AiosBug -Id $Target -Title "Auto Detected Bug"
    } else {
      $bugPath = ".\docs\bugs\$Target.md"
      $acceptancePath = ".\docs\acceptance\$Target.md"

      if ((-not (Test-Path -LiteralPath $bugPath)) -or (-not (Test-Path -LiteralPath $acceptancePath))) {
        New-AiosBug -Id $Target -Title "Auto Generated Bug"
      }
    }

    Write-Host "Target: $Target"
    Write-Host "Workflow: solve"
    Write-Host "Bug file: docs/bugs/$Target.md"
    Write-Host "Acceptance file: docs/acceptance/$Target.md"
    Write-Host ""
    Write-Host "Next: paste templates/AIOS_V9_SOLVE_PROMPT.md into your AI CLI."
  }

  "run" {
    Write-Header -Text "Run"

    if ([string]::IsNullOrWhiteSpace($Target)) {
      throw "Usage: powershell -ExecutionPolicy Bypass -File scripts\aios.ps1 run BUG-001"
    }

    Write-Host "Target: $Target"
    Write-Host "Use templates/AIOS_V9_SOLVE_PROMPT.md."
  }

  "release" {
    Write-Header -Text "Release"
    Write-Host "Release Manager should update version, changelog, release notes, commit message and PR description."
  }

  "resume" {
    Write-Header -Text "Resume"
    [void](Test-AiosFile -Path ".aios/snapshots/latest.json")
  }

  "rollback" {
    Write-Header -Text "Rollback"
    Write-Host "Rollback requires a selected snapshot from .aios/snapshots/."
  }

  "stats" {
    Write-Header -Text "Stats"
    Write-Host "Telemetry folder: .aios/telemetry/"
  }

  "start" {
    Write-Header -Text "Daemon Start"
    Write-Host "AIOS Daemon scaffold is ready."
    Write-Host "Capture logs in:"
    Write-Host "- .aios/logs/console.log"
    Write-Host "- .aios/logs/test.log"
    Write-Host "- .aios/logs/build.log"
  }

  default {
    throw "Unknown command: $Command"
  }
}
